background {
    monitor =
    path = /home/glauber/Images/Wallpapers/wallpaper_four.jpg
    blur_passes = 3
    blur_size = 1
}

image {
    path = /home/glauber/Images/Wallpapers/tux.jpg
    size = 140
    rounding = 70
    position = 0, 200
    halign = center
    valign = center
}

# Relógio
label {
    monitor =
    text = $TIME
    font_size = 72
    font_family = JetBrains Mono Nerd Font
    color = rgba(f0eaffff)
    halign = center
    valign = center
    position = 0, 30
}

# Data
label {
    monitor =
    text = cmd[update:60000] date "+%A, %d de %B"
    font_size = 20
    font_family = JetBrains Mono Nerd Font
    color = rgba(ffffffcc)
    halign = center
    valign = center
    position = 0, -40
}

input-field {
    monitor =
    size = 240, 35
    outline_thickness = 2
    dots_size = 0.3
    outer_color = rgb(515D84)      # violeta médio
    inner_color = rgba(4F90F766)   # roxo escuro semitransparente
    font_color = rgb(f0eaff)       # branco lilás
    placeholder_text = <i>Digite a senha...</i>
    hide_input = false
    fade_on_empty = false
    halign = center
    valign = center
    position = 0, -130
}
